/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Stitch Editorial Palette ──────────────────────────────
        "primary":                    "#003527",
        "primary-container":          "#064e3b",
        "on-primary":                 "#ffffff",
        "on-primary-container":       "#80bea6",
        "primary-fixed":              "#b0f0d6",
        "primary-fixed-dim":          "#95d3ba",
        "on-primary-fixed":           "#002117",
        "on-primary-fixed-variant":   "#0b513d",
        "secondary":                  "#5a605b",
        "secondary-container":        "#dee4de",
        "secondary-fixed":            "#dee4de",
        "secondary-fixed-dim":        "#c2c8c2",
        "on-secondary":               "#ffffff",
        "on-secondary-container":     "#606661",
        "on-secondary-fixed":         "#171d19",
        "on-secondary-fixed-variant": "#424844",
        "tertiary":                   "#23321f",
        "tertiary-container":         "#394934",
        "tertiary-fixed":             "#d5e8cb",
        "tertiary-fixed-dim":         "#b9ccb0",
        "on-tertiary":                "#ffffff",
        "on-tertiary-container":      "#a5b89c",
        "on-tertiary-fixed":          "#101f0d",
        "on-tertiary-fixed-variant":  "#3b4b36",
        "error":                      "#ba1a1a",
        "error-container":            "#ffdad6",
        "on-error":                   "#ffffff",
        "on-error-container":         "#93000a",
        "background":                 "#fafaf5",
        "on-background":              "#1a1c19",
        "surface":                    "#fafaf5",
        "surface-dim":                "#dadad5",
        "surface-bright":             "#fafaf5",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f4f4ef",
        "surface-container":          "#eeeee9",
        "surface-container-high":     "#e8e8e3",
        "surface-container-highest":  "#e3e3de",
        "surface-variant":            "#e3e3de",
        "surface-tint":               "#2b6954",
        "on-surface":                 "#1a1c19",
        "on-surface-variant":         "#404944",
        "outline":                    "#707974",
        "outline-variant":            "#bfc9c3",
        "inverse-surface":            "#2f312e",
        "inverse-on-surface":         "#f1f1ec",
        "inverse-primary":            "#95d3ba",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm:      "0.125rem",
        md:      "0.375rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
      boxShadow: {
        editorial: "0px 20px 40px rgba(26, 28, 25, 0.06)",
        lift:      "0px 8px 24px rgba(26, 28, 25, 0.10)",
      },
      backgroundImage: {
        "primary-gradient": "linear-gradient(135deg, #003527, #064e3b)",
      },
    },
  },
  plugins: [],
};
